name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update apt cache
        run: sudo apt-get update
      - name: Install apt dependencies
        run: sudo apt-get install -y lexicon ansible python3-pymysql
      - name: Run Ansible setup for debugging
        run: ansible localhost -c local -i localhost, -m setup
