name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update apt cache
        run: sudo apt-get update
      - name: Install apt dependencies
        run: sudo apt-get install -y lexicon ansible python3-pymysql virtinst libvirt-daemon-system
      - name: Start libvirt network
        run: sudo virsh net-start default
      - name: Run Ansible setup for debugging
        run: ansible localhost -c local -i localhost, -m setup
      - name: Create QEMU image
        run: sudo ./create.sh
      - name: Move installation ISO to a libvirt dir
        run: sudo mv debian-12.5.0-amd64-netinst.iso /var/lib/libvirt/images/
      - name: Run preseed install
        run: sudo ./install.sh
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: /var/lib/libvirt/images/debian.qcow2
