name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update apt cache
        run: sudo apt-get update
      - name: Install apt dependencies
        run: sudo apt-get install -y lexicon ansible python3-pymysql virtinst libvirt-daemon-system
      - name: Start libvirt network
        run: sudo virsh net-start default
      - name: Run Ansible setup for debugging
        run: ansible localhost -c local -i localhost, -m setup
      - name: Create QEMU image
        run: sudo qemu-img create -f qcow2 -o preallocation=metadata,lazy_refcounts=on debian.qcow2 10G
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: debian.qcow2
      - name: Run preseed install
        run: |
          virt-install \
            --connect qemu:///system \
            --network network=default,model=virtio \
            --graphics spice \
            --video virtio \
            --autoconsole text \
            --virt-type kvm \
            --name preseed \
            --os-variant=debian11 \
            --location debian-12.5.0-amd64-netinst.iso \
            --disk debian.qcow2 \
            --ram 4096 \
            --vcpus 2 \
            --initrd-inject preseed.cfg \
            --extra-args="ks=file:/preseed.cfg console=tty0 console=ttyS0,115200"
