name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update apt cache
        run: sudo apt-get update
      - name: Install apt dependencies
        run: sudo apt-get install -y lexicon ansible python3-pymysql virtinst
      - name: Run Ansible setup for debugging
        run: ansible localhost -c local -i localhost, -m setup
      - name: Create QEMU image
        run: sudo qemu-img create -f qcow2 -o preallocation=metadata,lazy_refcounts=on debian.qcow2 10G
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: debian.qcow2
