name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Python 'hello world' script
        run: python3 python/hello.py
      - name: Compile & run C 'hello world' program
        run: |
          gcc c/hello.c -o hello
          ./hello
