name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List directory files
        run: ls "${{ github.workspace }}"
      - name: Run Python 'hello world' script
        run: python3 python/hello.py
